### ISSUE TITLE
[매희] 게임 세션 개발을 위한 게임 입장 UI 필요

### ISSUE THREAD

**Issue by g0r0kke** [MTVS3FinalProject/MTVS3_Final_Unreal#24]
# 🙏요청사항

## Description

> 확인 시 comment 남기기, 진행상황 보고해주세요.

<br>

## To Do

- [x] 좌석 경쟁 UI 만들기
- [x] 플레이어는 로비 세션에 입장할 때부터 UI Factory에서 위젯을 꺼내 생성할 건데, 생성해야 하는 UI 정리(Comment)
- [x] 좌석 경쟁 UI 호출하는 방법 알려주기(Comment)

![image](https://github.com/user-attachments/assets/3ccee570-f554-42de-8cbe-477ec2a189f6)

<br>

## ETC

> 기타사항

**Comment by may-04** [comment]
좌석 경쟁 UI 호출하는 방법 : UMH_TicketingWidget->SetWidgetSwitcher(1) //0번은 좌석접수(현민), 1번은 경쟁입장(희진)
입장 버튼  실행 함수 :  OnClickedGotoGameRoomButton() 요거에요~
UI Factory생성 UI : 일단은 WBP_MainUI, WBP_TicketingUI 인데 추후 추가 될 수 있음
