### ISSUE TITLE
[희지니] UI 함수 연결 가이드

### ISSUE THREAD

**Issue by may-04** [MTVS3FinalProject/MTVS3_Final_Unreal#44]
# 🙏요청사항

## Description

> 확인 시 comment 남기기, 모두 완료되면 Close 해주세요.

<br>

(게임 화면) MH_GameStartCountDown 클래스
- 게임 레벨 이동 후 티켓팅 추첨 5초 남았을 때 플레이 필요.  // HallMap에 CountDown GUI 배치 해놓았슴다.
- 카운트다운 시작하는 함수 :  StartCountdown() 
- 카운트다운 스크린 비지블 : StartCountDownVisible(bool bIsvisible) 함수 이용.

- 현재 인원 : SetTextCurrentPlayer(int32 CurrentPlayer)

- 유저 좌석 번호 : SetTextMyNum() 
- 룰렛 1 결과 : SetTextroulette1()   
- 룰렛 2 결과 : SetTextroulette2() // 0 :"과(와) 같은 열만" /1:"과(와) 같은 행만"/2:"과(와) 같은 열 제외"/3:"과(와) 같은 행 제외"/4:"만"
- 룰렛 3 결과 : SetTextroulette3() // 0: 통과 / 1: 탈락
- 룰렛 애니메이션 플레이 : PlayRouletteAnim()

-위젯스위처
SetWidgetSwitcher(int32 num) : //0:현재인원,타이머/1: 룰렛 / 2: 축하~

**Comment by g0r0kke** [comment]
반영하겠습니당

**Comment by g0r0kke** [comment]
* 추가 필요사항 ! 코멘트로 정리해주세여
1. 카운트다운: nativeconstruct에서 숫자 visible false
2. 카운트다운: 시작하면 숫자 visible true
3. 룰렛: setwidgetSwitcher(1)했을 때 1인 경우에는 룰렛이 내려오는 애니메이션 재생 필요
4. 게임 UI: 플레이어 자기 좌석 번호 UI만 보이게 하는 함수

**Comment by may-04** [comment]
룰렛 Game UI
1. -> SetOnlyVisibleMyNum(bool bIsVisible) : 자기 번호만 남기고 비지블 껐다 켰다 함수 
 2. SetWidgetSwitcher num 이 1 일 때 룰렛 내려오는 애니메이션(PlayRouletteAnim04()) 실행, 
 3. 카운트다운 숫자 5 처음에 안보이게

**Comment by g0r0kke** [comment]
완료 -> 카운트다운 때 좌석 번호 보이는 것만 하면 됨
