### ISSUE TITLE
[희지니] countDown

### ISSUE THREAD

**Issue by may-04** [MTVS3FinalProject/MTVS3_Final_Unreal#47]
# 🙏요청사항

## Description

> 확인 시 comment 남기기, 모두 완료되면 Close 해주세요.

// countDown 액터로 변경

- MH_CountDownActor 클래스
-StartCountDownVisible(bool visible) 함수 호출 하면 되염 true는 카운트다운 시작, false는 this->Destroy

**Comment by g0r0kke** [comment]
네 적용할게영~~

**Comment by g0r0kke** [comment]
완료
