### ISSUE TITLE
[매히언니] 플레이어 이모티콘 애니메이션 설정 방법

### ISSUE THREAD

**Issue by g0r0kke** [MTVS3FinalProject/MTVS3_Final_Unreal#73]
# 🙏요청사항

## Description

> KHJ-Assets-Anim에 이모티콘 애니메이션 몽타주 넣어놨어여
> 확인 시 comment 남기기, 모두 완료되면 Close 해주세요.

<br>

## To Do
![image](https://github.com/user-attachments/assets/93f14d6c-1ae6-4d99-bfcf-7588688bc593)
* EmojiNum: 1(excited), 2(thumbs up), 3(clapping), 4(waving), 5(crying)
- [x] 리타겟팅한 애니메이션 블루프린트 디테일창에 Emoji Montage 채우기
![image](https://github.com/user-attachments/assets/6f3712de-d2f7-49d5-8106-9228caf7c71d)
- [x] 이모티콘 UI 눌렀을 때 다음 플레이어 함수 호출
UFUNCTION(Server , Reliable)
void ServerPlayEmojiAnim(const int32& EmojiNum);

<br>

## ETC

> 기타사항

**Comment by may-04** [comment]
네넹~

**Comment by g0r0kke** [comment]
완료 확인
